branches:
  only:
    - master
skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "8.10.0"
    - nodejs_version: "10.13.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - yarn lint
  - yarn test:ci

build: off
